name: deploy-api
triggers:
  - manual
steps:
  - name: build
    run: echo "building"
  - name: test
    run: echo "testing"
    needs: [build]
  - name: lint
    run: echo "linting"
    needs: [build]
  - name: deploy
    run: echo "deploying"
    needs: [test, lint]
  - name: preprocess
    executor: python
    run: scripts/preprocess.py
  - name: deployed
    executor: shell
    run: ./deploy.sh
maxParallel: 3
stopOnFail: true
retry: 2
